### ISSUE TITLE
Entangled Ring

### ISSUE THREAD

**Issue by JonReed90** [denbukki/Baublelicious#10]
Not sure if this is indeed an issue or something intended but not mentioned. Rings that grant vis discounts don't apply the discount when entangled.

**Comment by jamesbirtles** [comment]
Its sort of a limitation. Thaumcraft checks for the ring type and sees entangled rather than the vis ones.

**Comment by elifoster** [comment]
Why not give the Entangled thing a vis discount of the total vis discounts of all its entangled Baubles? I'm not very familiar with Thaumcraft, but I am pretty sure that this could easily be possible given you have written proper APIs for your Bauble items.

Also, it's generally bad practice to close wontfix issues, as closing them implies they were indeed fixed.
