### ISSUE TITLE
Entanglement not Working with Thaumcraft Baubles,

### ISSUE THREAD

**Issue by ThatOneTraitor** [denbukki/Baublelicious#12]
i was trying to entangle the runic rings and vis discount rings from thaumcraft onto an entangled ring, it didn't give the vis discount or runic shielding. I tried with the belts too, it didnt give me runic shielding. i'm not sure what github to report this to, so i'm starting here.

Versions of mods used:
Baubles 1.0.1.1.0
Baublelicious 1.7.10-1.2.1
Thaumcraft 4.2.3.5

**Comment by jamesbirtles** [comment]
It is based on the way thaumcraft gives those effects. The entangled baubles will generally only work on baubles that give an effect to the player. In order to support the runic and vis baubles I would have to add specific compatibility for thaumcraft which I don't plan on doing any time soon.

**Comment by ThatOneTraitor** [comment]
Wow, that was a quick response o.o, thanks though
