### ISSUE TITLE
Entangled Baubles don't work with Thaumcraft baubles

### ISSUE THREAD

**Issue by zclimber** [denbukki/Baublelicious#13]
Runic armor baubles - don't give runic armor, out-of-charge effects don't work either. Apprentice ring of Aer/Ignis/etc - don't give their vis discount. In other words, none work.
Althrough, this look like Thaumcraft only problem, for example Baubles Stuff - it's baubles work while entangled. 
Minecraft 1.7.10, Forge 1614, Baubles 1.0.1.10, Baublelicious 1.2.1, Thaumcraft 4.2.3.5.

**Comment by jamesbirtles** [comment]
See #10 and #12
