### ISSUE TITLE
night vision amulet needs epilepsy warning...

### ISSUE THREAD

**Issue by koalalord9999** [denbukki/Baublelicious#14]
its very flickery in the 1.7.2 version of project Ozone. Hurts my eyes, and doesn't show theres a buff fro night vision. if you could change it so theres a infinite timer for it, that would be nice

**Comment by jamesbirtles** [comment]
Been fixed since may.. 
https://github.com/UnwrittenFun/Baublelicious/commit/d1ca09afc8b42670e4677b6ea5aa5e3e85844687

**Comment by koalalord9999** [comment]
Are you sure? http://prntscr.com/ambxcx I'm not saying I don't believe you, but... it uses the same version as the latest you have uploaded on curseforge.

**Comment by Psithief** [comment]
@UnwrittenFun but still very problematic in 1.2.1. 
Buff constantly flicks on and off, displaying `0:49` for duration.

**Comment by ghost** [comment]
i wil take a look at it today. im working on a final version for 1.7.10 before releasing the update to 1.10

**Comment by Psithief** [comment]
@denbukki Very nice. Cheers.

**Comment by ghost** [comment]
release available on curse

**Comment by Psithief** [comment]
@denbukki I've tested this and didn't get any improvement.
I don't think the duration was the issue. I'm going to find this incompatibility for you and get back to you on this.

**Comment by ghost** [comment]
did you use it in combination wih any other mods or specific graphics settings?

**Comment by ghost** [comment]
it shouldnt be happening because its not updating at all. because now it adds an infinite effect and removes it when unequiped.

**Comment by Psithief** [comment]
That's what I'm eliminating right now, starting from no mods (botania + this one) and re-enabling them until it occurs. 

There are other mods that have night vision that don't conflict, which is why it looked like this mod was the problem.

**Comment by ghost** [comment]
i wont be updating 1.7.10 anymore this was the final version. i wil now be focusing on 1.11. so this is kinda pointless

**Comment by Psithief** [comment]
It is, but if you don't mind I'd like to record what I find here for the next person. 

For any future readers:
The incompatible mod is `The Erebus`. 
The issues for that mod is at https://github.com/ganymedes01/TheErebus/issues
