### ISSUE TITLE
Entangled ring and Botania

### ISSUE THREAD

**Issue by peter-ssk** [denbukki/Baublelicious#16]
Hello, I found that **Botania's ring**s like Greater band of mana and relics, isn't working in the **Entangled ring**, it doesn't store anymore mana when it's in the entangled ring, the same for relics ring, they doesn't apply effects when it is on the entangled ring.
And by the way I didn't find a way to extract them from the entangled ring, so they are lost. 

I hope you will update your mod, because I seen the last update was from the last year :)

PS: Sorry for my bad english, don't be mad at me please :P

**Comment by ghost** [comment]
the Entangled baubles use the default effect functions of baubles. the baubles of botania that use mana in any way cant find the mana because the ring isnt equiped by the player. there is no way to fix this without specificly using the botania api
