### ISSUE TITLE
Entangled Rings

### ISSUE THREAD

**Issue by DeflatedPickle** [denbukki/Baublelicious#18]
To be able to use more rings, I crafted a few of my rings together with an Entangled Ring. My other rings being a Magnet Ring and a ring from Artifacts. Now that they are both in an Entangled Ring, I can not edit the blacklist of the Magnet Ring, this is quite unhelpful.
I feel it would be better if the ring would open a small inventory (probably 9 slots) when the use button and the crouch button where pressed, this inventory would then be used to store rings. This way, anyone with an Entangled Ring could take out and swap the rings inside.

**Comment by ghost** [comment]
Hi, currently development for 1.7.10 has stopped. but we will consider adding it to the 1.11 version
