### ISSUE TITLE
Conflict with Storage Drawers (visual only i think)

### ISSUE THREAD

**Issue by corgiblu** [denbukki/Baublelicious#20]
Having storage drawers and this mod installed cause the magic cores to be the "broken" texture. The black and purple checkers. I already confirmed this is not caused by storage drawers dependency chameleon.

Versions:
Babuleicious 1.4.0-4
Baubles 1.12-1.5.2
Chameleon 1.12-4.1.3
Storage Drawers 1.12.2-5.3.7

**Comment by corgiblu** [comment]
jaquadro/StorageDrawers/issues/666

**Comment by dennisblokland** [comment]
The chance is small I will work on the mod in the near future and when I will I'll be working on a port. I'll leave the issue open for reference but consider it a won't fix.

**Comment by corgiblu** [comment]
All right
