### ISSUE TITLE
Implement a fake equip and unequip for pedestal

### ISSUE THREAD

**Issue by jamesbirtles** [denbukki/Baublelicious#6]
Right now the pedestal just reports a 'wear' tick which is not enough for some baubles (e.g. flight, step assist). These need the equip and unequip calls to setup and remove abilities respectively.
### Unequip when
- Pedestal is broken
- Bauble is removed/replaced
- Binding gem is removed/changed
- Player goes out of range
  - This will likely require tracking the player that we have 'equipped' the bauble to.
### Equip when
- Pedestal loads (world load)
- Bauble is inserted and Gem is already there
- Gem is inserted and Bauble is already there
- Gem is swapped out
- Player comes into range (see above for tracking)

**Comment by ghost** [comment]
UnwrittenFun you are taking over Baublelicious? Well tell me if you need
any sprites or small amounts of code (I'm not great at Java but decent I
guess)

**Comment by jamesbirtles** [comment]
Yes I am, and I could do with some textures. I'll create an issue and assign you to it whenever I need one if you're okay with that? Thanks!

**Comment by ghost** [comment]
Will I get an email?

**Comment by jamesbirtles** [comment]
Err, I think so.. I'll try it

**Comment by jamesbirtles** [comment]
Theoretically you should have an email about it now
