### ISSUE TITLE
Entangled Baubles

### ISSUE THREAD

**Issue by jamesbirtles** [denbukki/Baublelicious#9]
I need 3 textures.
- Entangled Belt
- Entangled Ring
- Entangled Amulet

They will all do essentially the same thing which is allow you to wear more than one of the respective bauble types. E.g. you could wear a falling belt and a water walking belt at the same time.

**Comment by ghost** [comment]
Been a long time. I will make that texture if you want and the mod is not dead. Just sort of a red gem thing?
